import {
  AlertTriangle,
  ArrowLeft,
  Briefcase,
  Calendar,
  CalendarDays,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Download,
  Eye,
  FilePen,
  FileText,
  Inbox,
  LayoutDashboard,
  ListChecks,
  Loader2,
  LogOut,
  Menu,
  MessageSquare,
  Pencil,
  Plus,
  Search,
  Send,
  Settings,
  Shield,
  SlidersHorizontal,
  SquareStack,
  Trash2,
  TrendingUp,
  Upload,
  User,
  User2,
  Users,
  X,
} from 'lucide-react';

export const DASHBOARD_ICONS = {
  LAYOUTDASHBOARD: LayoutDashboard,
  CHECKCIRCLE: CheckCircle,
  SHIELD: Shield,
  TRENDINGUP: TrendingUp,
  USERS: Users,
  FILETEXT: FileText,
  FILEPEN: FilePen,
  CALENDARDAYS: CalendarDays,
  EYE: Eye,
  PENCIL: Pencil,
  TRASH2: Trash2,
  PLUS: Plus,
  INBOX: Inbox,
  SEARCH: Search,
  CHEVRONLEFT: ChevronLeft,
  CHEVRONRIGHT: ChevronRight,
  ARROWLEFT: ArrowLeft,
  USER: User,
  USER2: User2,
  ALERTTRIANGLE: AlertTriangle,
  UPLOAD: Upload,
  SETTINGS: Settings,
  LOGOUT: LogOut,
  CALENDAR: Calendar,
  SQUARESTACK: SquareStack,
  LISTCHECKS: ListChecks,
  CHEVRONDOWN: ChevronDown,
  MENU: Menu,
  LOADER2: Loader2,
  CLOCK: Clock,
  BRIEFCASE: Briefcase,
  FILTER: SlidersHorizontal,
  CLOSE: X,
  DOWNLOAD: Download,
  SEND: Send,
  MESSAGESQUARE: MessageSquare,
};
