import {
  LayoutDashboard,
  CheckCircle,
  Shield,
  TrendingUp,
  Users,
  FileText,
  FilePen,
  CalendarDays,
  Eye,
  Pencil,
  Trash2,
  Plus,
  Inbox,
  Search,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  User,
  AlertTriangle,
  Upload,
  Settings,
  LogOut,
  Calendar,
  SquareStack,
  ListChecks,
  User2,
  ChevronDown,
  Menu,
  Loader2,
} from "lucide-react";

export const DASHBOARD_ICONS = {
  LAYOUTDASHBOARD: LayoutDashboard,
  CHECKCIRCLE: CheckCircle,
  SHIELD: Shield,
  TRENDINGUP: TrendingUp,
  USERS: Users,
  FILETEXT: FileText,
  FILEPEN: FilePen,
  CALENDARDAYS: CalendarDays,
  EYE: Eye,
  PENCIL: Pencil,
  TRASH2: Trash2,
  PLUS: Plus,
  INBOX: Inbox,
  SEARCH: Search,
  CHEVRONLEFT: ChevronLeft,
  CHEVRONRIGHT: ChevronRight,
  ARROWLEFT: ArrowLeft,
  USER: User,
  USER2: User2,
  ALERTTRIANGLE: AlertTriangle,
  UPLOAD: Upload,
  SETTINGS: Settings,
  LOGOUT: LogOut,
  CALENDAR: Calendar,
  SQUARESTACK: SquareStack,
  LISTCHECKS: ListChecks,
  CHEVRONDOWN: ChevronDown,
  MENU: Menu,
  LOADER2: Loader2,
};
