import {
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  CheckCircle,
  ChevronRight,
  Clock,
  Code,
  Copy,
  ExternalLink,
  Eye,
  FileCode,
  FileText,
  Hash,
  Heart,
  Home,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Lock,
  LogIn,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Moon,
  Phone,
  Play,
  Rocket,
  ScrollText,
  Send,
  Server,
  Shield,
  ShieldCheck,
  Sparkles,
  Sun,
  Target,
  Terminal,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react';
import {
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaLinkedin,
  FaTelegram,
  FaTwitter,
} from 'react-icons/fa';

export const GUEST_ICONS = {
  HOME: Home,
  USER: User,
  LOGIN: LogIn,
  INFO: Info,
  MAIL: Mail,
  MENU: Menu,
  CLOSE: X,
  SUN: Sun,
  MOON: Moon,
  DASHBOARD: LayoutDashboard,
  ARROW_RIGHT: ArrowRight,
  ZAP: Zap,
  SHIELD: Shield,
  CHECK: CheckCircle,
  TARGET: Target,
  HEART: Heart,
  LIGHTBULB: Lightbulb,
  USERS: Users,
  ROCKET: Rocket,
  SHIELD_CHECK: ShieldCheck,
  MESSAGE: MessageSquare,
  SEND: Send,
  MAP_PIN: MapPin,
  PHONE: Phone,
  CLOCK: Clock,
  CHART: BarChart3,
  SPARKLES: Sparkles,
  BOOK_OPEN: BookOpen,
  CODE: Code,
  TERMINAL: Terminal,
  KEY: Key,
  FILE_CODE: FileCode,
  LAYERS: Layers,
  COPY: Copy,
  EXTERNAL_LINK: ExternalLink,
  PLAY: Play,
  CHEVRON_RIGHT: ChevronRight,
  HASH: Hash,
  LOCK: Lock,
  SERVER: Server,
  BELL: Bell,
  FILE_TEXT: FileText,
  EYE: Eye,
  SCROLL_TEXT: ScrollText,

  // Social Icons
  TWITTER: FaTwitter,
  INSTAGRAM: FaInstagram,
  LINKEDIN: FaLinkedin,
  TELEGRAM: FaTelegram,
  FACEBOOK: FaFacebook,
  GITHUB: FaGithub,
};
