import {
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  Info,
  Loader2,
  MoreHorizontal,
  OctagonX,
  PanelLeft,
  TriangleAlert,
  X,
} from 'lucide-react';

export const UI_ICONS = {
  X: X,
  PANEL_LEFT: PanelLeft,
  CIRCLE_CHECK: CircleCheck,
  INFO: Info,
  TRIANGLE_ALERT: TriangleAlert,
  OCTAGON_X: OctagonX,
  LOADER2: Loader2,
  CHEVRON_DOWN: ChevronDown,
  CHECK: Check,
  CHEVRON_UP: ChevronUp,
  CHEVRON_LEFT: ChevronLeft,
  CHEVRON_RIGHT: ChevronRight,
  MORE_HORIZONTAL: MoreHorizontal,
};
